!******************************************************
! Input Homogenization Information for Solid Model    *
!                                                     *
! written by: Banghua Zhao                            *
! Date: 2015                                          *
!                                                     *
! Modified by: Banghua Zhao                           *
! Date: 2016                                          *
!******************************************************


/prep7
/NOPR

*abset, 'Solid Model Data processing', BAR

HD=3   !Homogenization Dimension

analysis=ARG1
ele_flag=ARG2
trans_flag=ARG3
temp_flag=ARG4
nslave=0
Solid_flag=1


!+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!C1DSG_flag not equal 1
!+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*IF, C1DSG_flag, NE, 1, THEN

H_node-no_y1_y2_y3,mac

*ENDIF
!+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++




!+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!C1DSG_flag equal 1
!+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*IF, C1DSG_flag, EQ, 1, THEN

H_C1D,mac

*ENDIF

/GOPR
