!******************************************************
! Input Homogenization Information for Beam Model     *
!                                                     *
! written by: Banghua Zhao                            *
! Date: 2015                                          *
!                                                     *
! Modified by: Banghua Zhao                           *
! Date: 2016                                          *
!******************************************************


/prep7
/NOPR

! Beam model cannot handle 1D SG
*if, C1DSG_flag, eq, 1, then
*MSG,ERROR
1D Structure Genome does not work for Beam Model%/&
Please choose Plate/Shell Model or Solid Model!
/EOF
*endif


*abset, 'Beam Model Data processing', BAR

HD=1   !Homogenization Dimension

TypeFlag=ARG1
k11=ARG2
k12=ARG3
k13=ARG4
cyx11=ARG5
cyx21=ARG6
analysis=ARG7
ele_flag=ARG8
trans_flag=ARG9
temp_flag=AR10
nslave=0
Beam_flag=1

H_node-no_y1_y2_y3,mac

/GOPR
